name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install Poetry
      run: pipx install poetry==2.0.1
    - name: Install dependencies
      run: poetry env use $(which python) && poetry install
    - name: Run linters
      run: make lint-check
